title: PHARE
description: Parallel Hybrid particle in cell code with Adaptive mesh REfinement
remote_theme: chrisrhymes/bulma-clean-theme
paginate: 5
paginate_path: "/blog/page:num"
permalink: prett
hero_image: https://user-images.githubusercontent.com/3200931/95620089-f13ebb80-0a6f-11eb-9af3-a1db08004bcc.png
